apiVersion: networking.k8s.io/v1beta
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: your.domain.com.
    name: nginx
spec:
  rules:
  - host: via-ingress.external-dns-test.your.domain.com.
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.external-dns-test.your.domain.com.
  name: nginx
  spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80    